import numpy as np

def write_stl(vertices, faces, normals, filename='output.stl'):
    with open(filename, 'w') as f:
        # Nagłówek pliku STL
        f.write("solid generated_by_python\n")

        # Zapisujemy trójkąty na podstawie współrzędnych wierzchołków
        for i in range(len(faces)):

            f.write("  facet normal {0} {1} {2}\n".format(normals[i][0], normals[i][1], normals[i][2]))
            f.write("    outer loop\n")

            for j in range(0, 3):
                f.write("      vertex {0} {1} {2}\n".format(vertices[faces[i][j]][0], vertices[faces[i][j]][1], vertices[faces[i][j]][2]))

            f.write("    endloop\n")
            f.write("  endfacet\n")

        # Zamknięcie pliku STL
        f.write("\nendsolid")
        f.write("\n;generated by ppjotrek\n")

    print(f'Plik STL został wygenerowany: {filename}')

# Przykładowe dane - zastąp je swoimi danymi

vertices = np.load('vertices.npy')
faces = np.load('faces.npy')
normals = np.load('normals.npy')

# Wywołanie funkcji generującej plik STL
write_stl(vertices, faces, normals)